hw_info:
  cpu_id: ""
  cpu_name: ck802
  vendor_name: ""
  chip_name: ""
  board_name: ""
  ld_script: ../../board/gcc_flash.ld
  flash_program: ""
def_config:
  CONFIG_ADC: 1
  CONFIG_ARCH_INTERRUPTSTACK: 1024
  CONFIG_DEBUG_MODE: 1
  CONFIG_KERNEL_NONE: 1
  CONFIG_SUPPORT_TSPEND: 1
  CONFIG_XIP: 1
  DBG_PRINT2PC: 1
  IS_CHIP_1101: 1
  IS_CHIP_1104: 1
name: apt110
version: v1.0.0
description: 我的第一个方案工程
tag: ""
keywords: 
author:
  name: ""
license: ""
type: solution
depends:
  - sdk_110x: v1.0.3
build_config:
  include:
    - include
    - src/include
    - ./
  internal_include: 
  cflag: -Os
  cxxflag: -Os
  asmflag: -Wa,--gdwarf2
  define: 
  libs: 
  libpath: 
source_file:
  - src/main.c
  - src/bootloader.c
depends_forward:
  - sdk_110x: v1.0.3
install: 
homepage: 